### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by lajiji** [SMARTlab-Purdue/robotarium-rendezvous-RSSDOA#2]
Hi, according to your steps, I ran "init. m" first, and then "rendezvous_ experiments_ Robotarium_ main. m ", the following error appears：
>> rendezvous_ experiments_ Robotarium_ main
Function or variable 'RobotariumBuilder' is not defined.
Error rendezvous_ experiments_ Robotarium_ main (line 37)
rb = RobotariumBuilder();

Do you know why?

**Comment by ramviyas** [comment]
So Robotarium has updated their simulator in their GitHub https://github.com/robotarium/robotarium-matlab-simulator/blob/master/examples/consensus_static/consensus.m

I assume you downloaded this repo and places all the RSSDOA repo contents to this folder.

Now, in the rendezvous_experiments_Robotarium_main.m file, 

Replace the lines:

%% Get Robotarium object used to communicate with the robots/simulator
rb = RobotariumBuilder();
% Build the Robotarium simulator object!
r = rb.set_number_of_agents(N).set_save_data(false).build();
figure_robotarium = figure(1); movegui('northeast'); movegui('onscreen');
%title('Rendezvous algorithm experimented in Robotarium testbed');


With the below lines (see one of the Robotarium’s own examples)

%% Get Robotarium object used to communicate with the robots/simulator
r = Robotarium('NumberOfRobots', N, 'ShowFigure', true);
